/**:
  ros__parameters:
    # -- system --
    traj_resample_dist: 0.1         
    use_steer_prediction: false     
    use_delayed_initial_state: true 

    # -- path smoothing --
    # 建議維持開啟，但參數微調。低速車不需要過度平滑，改為 15 點即可，反應會比較快。
    enable_path_smoothing: true   
    path_filter_moving_ave_num: 15 
    curvature_smoothing_num_traj: 15        
    curvature_smoothing_num_ref_steer: 15   

    # -- trajectory extending --
    extend_trajectory_for_end_yaw_control: false  

    # -- mpc optimization --
    qp_solver_type: "osqp"                       
    mpc_prediction_horizon: 50                   
    mpc_prediction_dt: 0.1                       
    mpc_weight_lat_error: 1.0                    
    
    # [關鍵修改 1] 航向誤差權重
    # 既然 steer_rate 不能高，我們必須靠這個來穩住車身。
    # 從 0.3 提升到 1.0。這會讓車子更積極地讓車頭對準路徑，減少蛇行。
    mpc_weight_heading_error: 1.0                
    mpc_weight_heading_error_squared_vel: 0.3    
    
    mpc_weight_steering_input: 1.0               
    mpc_weight_steering_input_squared_vel: 0.25  
    mpc_weight_lat_jerk: 0.1                     
    
    # [遵守你的實驗限制] 
    # 維持 0.05。這數值很低，代表阻尼很弱，所以上面的 heading_error 必須夠強才拉得住。
    mpc_weight_steer_rate: 0.05                   
    mpc_weight_steer_acc:  0.00001               
    
    # [關鍵修改 2] 直線 (Low Curvature) 鎖定邏輯
    # 在偵測到幾乎是直線時 (曲率 < 0.02)，我們開啟「強硬模式」。
    # 這裡的 weight 可以設高一點，因為直線行駛時，方向盤本來就不該動。
    mpc_low_curvature_thresh_curvature: 0.02                    
    mpc_low_curvature_weight_lat_error: 0.1                    
    mpc_low_curvature_weight_heading_error: 2.0                # 直線時，車頭歪一點點都要重罰
    mpc_low_curvature_weight_heading_error_squared_vel: 0.3    
    mpc_low_curvature_weight_steering_input: 1.0               
    mpc_low_curvature_weight_steering_input_squared_vel: 0.25  
    mpc_low_curvature_weight_lat_jerk: 0.5                     # 提高 Jerk 懲罰，讓直線修正更柔和
    mpc_low_curvature_weight_steer_rate: 0.05                  # 這裡也必須遵守你的 0.05 限制，以免直線修正時也不轉了
    mpc_low_curvature_weight_steer_acc: 0.00001              
    
    mpc_weight_terminal_lat_error: 1.0           
    mpc_weight_terminal_heading_error: 0.5       #稍微提高終點航向權重
    mpc_zero_ff_steer_deg: 0.5                   
    mpc_acceleration_limit: 2.0                  
    mpc_velocity_time_constant: 0.3              
    mpc_min_prediction_length: 5.0               

    # -- vehicle model --
    vehicle_model_type: "kinematics" 
    input_delay: 0.24                
    vehicle_model_steer_tau: 0.27     
    
    # [關鍵修改 3] 速度映射修正
    # 你的車速是 0~2.8 m/s (10km/h)。
    # 原本的 [10, 15, 20] 完全無效。修正如下：
    steer_rate_lim_dps_list_by_curvature: [40.0, 50.0, 60.0]            
    curvature_list_for_steer_rate_lim: [0.01, 0.05, 0.1]              
    
    # 這裡非常重要：
    # 將速度區間改為 1.0, 2.0, 3.0 m/s。
    # 這樣你的 10km/h (2.8m/s) 就會落在有效控制範圍內。
    steer_rate_lim_dps_list_by_velocity: [60.0, 45.0, 30.0]             
    velocity_list_for_steer_rate_lim: [1.0, 2.0, 3.0]                  
    
    acceleration_limit: 2.0          
    velocity_time_constant: 0.3      

    # -- lowpass filter for noise reduction --
    steering_lpf_cutoff_hz: 3.0 
    error_deriv_lpf_cutoff_hz: 5.0

    # stop state
    stop_state_entry_ego_speed: 0.001
    stop_state_entry_target_speed: 0.001
    converged_steer_rad: 0.1
    keep_steer_control_until_converged: true
    new_traj_duration_time: 1.0
    new_traj_end_dist: 0.3
    mpc_converged_threshold_rps:  0.01 

    # steer offset
    steering_offset:
      enable_auto_steering_offset_removal: true
      # [修正] 啟用自動校正的門檻。原本 5.56 太高，改為 2.0 m/s。
      # 這樣你的車在跑 10km/h 時，系統就能自動學習方向盤是否有歪掉。
      update_vel_threshold: 2.0
      update_steer_threshold: 0.035
      average_num: 1000
      steering_offset_limit: 0.02

    publish_debug_trajectories: true
