/**:
  ros__parameters:
    # -- system --
    traj_resample_dist: 0.1         
    use_steer_prediction: false     
    use_delayed_initial_state: true 

    # -- path smoothing --
    enable_path_smoothing: true   
    path_filter_moving_ave_num: 15 
    curvature_smoothing_num_traj: 15        
    curvature_smoothing_num_ref_steer: 15   

    # -- trajectory extending --
    extend_trajectory_for_end_yaw_control: false  

    # -- mpc optimization --
    qp_solver_type: "osqp"                       
    
    # === [性能優化核心] ===
    # 問題：改版二太慢，導致掉幀 (Max Latency > 100ms)。
    # 原因：權重太嚴格，Solver 算不出來。
    # 解法：大幅減少預測步數。
    # 在 10km/h (2.78m/s) 下，看 3.75秒 (約10公尺) 已經非常足夠反應。
    # 從 40 降到 25，運算量幾乎減半，能有效救回延遲。
    mpc_prediction_horizon: 25                   
    mpc_prediction_dt: 0.15                       

    # === [權重微調] ===
    # 稍微放寬一點點側向誤差 (3.0 -> 2.5)，讓 Solver 更容易收斂，減少卡頓。
    # 但 2.5 依然是很高的數值，防撞牆能力應該還在。
    mpc_weight_lat_error: 2.5                    
    
    mpc_weight_heading_error: 1.0                
    mpc_weight_heading_error_squared_vel: 0.3    
    mpc_weight_steering_input: 1.0               
    mpc_weight_steering_input_squared_vel: 0.25  
    mpc_weight_lat_jerk: 0.1                     
    
    # [維持限制]
    mpc_weight_steer_rate: 0.05                   
    mpc_weight_steer_acc:  0.00001               
    
    # === [直線模式] ===
    mpc_low_curvature_thresh_curvature: 0.02                    
    
    # 直線模式保持嚴格，因為直線運算比較簡單，不太會卡頓
    mpc_low_curvature_weight_lat_error: 0.5                    
    mpc_low_curvature_weight_heading_error: 2.0                
    mpc_low_curvature_weight_heading_error_squared_vel: 0.3    
    mpc_low_curvature_weight_steering_input: 1.0               
    mpc_low_curvature_weight_steering_input_squared_vel: 0.25  
    mpc_low_curvature_weight_lat_jerk: 0.5                     
    mpc_low_curvature_weight_steer_rate: 0.05                  
    mpc_low_curvature_weight_steer_acc: 0.00001              
    
    mpc_weight_terminal_lat_error: 1.0           
    mpc_weight_terminal_heading_error: 0.5       
    mpc_zero_ff_steer_deg: 0.5                   
    mpc_acceleration_limit: 2.0                  
    mpc_velocity_time_constant: 0.3              
    mpc_min_prediction_length: 5.0               

    # -- vehicle model --
    vehicle_model_type: "kinematics" 
    input_delay: 0.24                
    vehicle_model_steer_tau: 0.27     
    
    # === [速度與轉向限制] ===
    # 維持改版二的設定，這對低速車是正確的
    steer_rate_lim_dps_list_by_curvature: [40.0, 50.0, 60.0]            
    curvature_list_for_steer_rate_lim: [0.01, 0.05, 0.1]              
    
    steer_rate_lim_dps_list_by_velocity: [60.0, 50.0, 45.0]             
    velocity_list_for_steer_rate_lim: [1.0, 2.0, 3.0]                  
    
    acceleration_limit: 2.0          
    velocity_time_constant: 0.3      

    # -- lowpass filter for noise reduction --
    steering_lpf_cutoff_hz: 3.0 
    error_deriv_lpf_cutoff_hz: 5.0

    # stop state
    stop_state_entry_ego_speed: 0.001
    stop_state_entry_target_speed: 0.001
    converged_steer_rad: 0.1
    keep_steer_control_until_converged: true
    new_traj_duration_time: 1.0
    new_traj_end_dist: 0.3
    mpc_converged_threshold_rps:  0.01 

    # steer offset
    steering_offset:
      enable_auto_steering_offset_removal: true
      update_vel_threshold: 2.0
      update_steer_threshold: 0.035
      average_num: 1000
      steering_offset_limit: 0.02

    publish_debug_trajectories: true
